services:
  - type: web
    name: dorkhunter-webapp
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: "ta_cle_openai"
    autoDeploy: true
